######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 13 17:18:00 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += "Jaya Naga Bhavana Kommuru.cpp"
